#!/bin/zsh
setopt prompt_subst

autoload -Uz vcs_info

zstyle ':vcs_info:*' stagedstr '%F{28}●'
zstyle ':vcs_info:*' unstagedstr '%F{11}●'
zstyle ':vcs_info:*' check-for-changes true
zstyle ':vcs_info:(sv[nk]|bzr):*' branchformat '%b%F{1}:%F{11}%r'
zstyle ':vcs_info:*' enable git svn

function battery_charge {
  echo $(battery.py) 2> /dev/null
}

function prompt_char {
    git branch >/dev/null 2>/dev/null && echo '±' && return
    hg root >/dev/null 2>/dev/null && echo '☿' && return
    echo '○'
}

precmd () {
    if [[ -z $(git ls-files --other --exclude-standard 2> /dev/null) ]] {
        zstyle ':vcs_info:*' formats '%F{green}%b%u'
    } else {
        zstyle ':vcs_info:*' formats '%F{green}%b%u%F{red}●'
    }

    vcs_info
}

setopt prompt_subst

function setprompt {
  ###
  # Need this so the prompt will work.
  setopt prompt_subst

  ###
  # See if we can use colors.
  autoload colors zsh/terminfo
  if [[ "$terminfo[colors]" -ge 8 ]]; then
    colors
  fi

  for color in RED GREEN YELLOW BLUE MAGENTA CYAN WHITE; do
    eval PR_$color='%{$terminfo[bold]$fg[${(L)color}]%}'
    eval PR_LIGHT_$color='%{$fg[${(L)color}]%}'
    (( count = $count + 1 ))
  done
  PR_NO_COLOUR="%{$terminfo[sgr0]%}"

  ###
  # Finally, the prompt.
  PROMPT='$(prompt_char) %~ ${vcs_info_msg_0_}$PR_BLUE %(?/%F{blue}/%F{red})$PR_RED → $PR_NO_COLOUR '
  RPROMPT='$(battery_charge)'
  PS2='$PR_RED → $PR_BLUE %_ $PR_RED → $PR_NO_COLOUR '

}

setprompt
