.TH DATEDIFF 1
.SH NAME
datediff \- show the delta between two dates
.SH SYNOPSIS
.B datediff
.R [OPTIONS] DATE1 [DATE2]
.SH DESCRIPTION
Show the different between DATE1 and DATE2 in a variety of units.
.SH OPTIONS
.TP
.BR \-h ", "\-\-help
Display help and exit.
.TP
.BR \-d ", "\-\-debug
Enable the Lisp debugger.
